export default `a-certain-smile
a-day-in-the-life-of-a-fool
a-felicidade
a-fine-romance
a-foggy-day
a-fool-such-as-i
a-ghost-of-a-chance
a-kiss-to-build-a-dream-on
a-lot-of-livin-to-do
a-nightingale-sang-in-berkeley-square
a-red-red-rose
a-shine-on-your-shoes
a-white-sport-coat
a-wonderful-day-like-today
aba-daba-honeymoon
abracadabra
abrazame-asi
act-naturally
adios-muchachos
after-youve-gone
again
aint-misbehavin
aint-we-got-fun
al-di-la
alardoso
alexanders-ragtime-band
alfie
alice-blue-gown
alivio
all-er-nothin
all-gods-chillun-got-rhythm
all-i-have-to-do-is-dream
all-i-need-is-the-girl
all-my-love
all-of-me
all-the-things-you-are
all-time-high
alley-cat-song
alma-de-mujer
almost-like-being-in-love
alright-okay-you-win
always-in-my-heart
always-true-to-you-in-my-fashion
always
am-i-blue
amapola
among-my-souvenirs
amor
and-the-angels-sing
angel-eyes
anna
annies-song
anniversary-song
another-opnin-another-show
another-somebody-done-somebody-wrong
any-time
anything-but-love
anything-goes
april-in-portugal
april-showers
aquarius
are-you-havin-any-fun
are-you-lonesome-tonight
are-you-sincere
arrancame-la-vida
arrivederci-roma
as-time-goes-by
at-last
at-long-last-love
at-sundown
at-the-jazzband-ball
aunt-hagars-blues
autumn-in-new-york
autumn-leaves
avalon
baby-elephant-walk
baby-face
back-in-your-own-backyard
bad-leroy-brown
ballin-the-jack
baltimore-oriole
baubles-bangles-and-beads
be-anything
beatrice
because-of-you
beer-barrel-polka
begin-the-beguine
behind-closed-doors
bei-mir-bist-du-schon
bella-notte
besame-mucho
best-is-yet-to-come
best-thing-for-you
best-things-in-life-are-free
beyond-the-reef
beyond-the-sea
bibbidi-bobbidi-boo
bidin-my-time
big-spender
bill-bailey-wont-you-please-come-home
birth-of-the-blues
black-coffee
blame-it-on-my-youth
blame-it-on-the-bossa-nova
blind-ploughman
blow-gabriel-blow
blue-and-sentimental
blue-bayou
blue-bossa
blue-moon
blue-on-blue
blue-room
blue-skies
blue-velvet
blueberry-hill
blues-in-the-night
blues-my-naughty-sweetie-gives-to-me
bluesette
body-and-soul
bogalusa-strut
boo-hoo
boulevard-of-broken-dreams
brazil
breeze-and-i
breezin-along-with-the-breeze
bridge-over-troubled-water
brother-can-you-spare-a-dime
brown-skin-girl
brussels-in-the-rain
buster-rides-again
but-beautiful
but-not-for-me
button-up-your-overcoat
bye-bye-blackbird
bye-bye-blues
bye-bye-love
ca-cest-lamour
cabaret
cachita
calculadora
california-dreamin
call-me-irresponsible
call-me
canadian-sunset
canal-street-blues
candy
cant-help-falling-in-love
cant-help-lovin-dat-man
cant-yo-heah-me-callin-caroline
caravan
carinhoso
carioca
carolina-in-the-morning
carolina-moon
cast-your-fate-to-the-wind
cest-magnifique
cest-si-bon
change-partners
charleston-parisien
charleston
charmaine
chattanooga-choo-choo
cheek-to-cheek
chelsea-bridge
cherish
cherrypink
chicago
chicken-feed
chitlins-con-carne
choo-choo-ch-boogie
cindy-oh-cindy
clap-hands-here-comes-charlie
cleopatra-had-a-jazz-band
close-to-you
close-your-eyes
clouds
cold-cold-heart
come-rain-or-come-shine
come-saturday-morning
come-sunday
come-to-the-mardi-gras
comes-love
como-fue
compadre-pedro-juan
con-tres-palabras
constant-rain
contigo-en-la-distancia
continental
convergencia
cool-water
copacabana
corrine-corrina
cotton-candy
count-every-star
count-your-blessings-instead-of-sheep
crazy
cross-over-the-bridge
cruising-down-the-river
cry-me-a-river
cry
crying
cuddle-up-a-little-closer
cute
dance-only-with-me
dancing-in-the-dark
dancing-on-the-ceiling
dansero
dardanella
darkness-on-the-delta
darktown-strutters-ball
dat-dere
day-o
daydream
days-of-wine-and-roses
dedicated-to-the-one-i-love
deep-in-a-dream
deep-purple
deep-river-blues
delicado
delilah
desafinado
diamonds-are-a-girls-best-friend
did-you-ever-see-a-dream-walking
dinah
dindi
dipsy-doodle
django
do-do-do
do-nothin-till-you-hear-from-me
do-you-know-what-it-means-to-miss-new-orleans
dock-of-the-bay
doggie
dolphin
domino
dont-blame-me
dont-bring-lulu
dont-ever-go-away
dont-explain
dont-fence-me-in
dont-get-around-much-anymore
dont-let-it-bother-you
dont-sit-under-the-apple-tree
dos-gardenias
down-with-love
downtown
dream-a-little-dream-of-me
dream-lover
dream
dreamsville
drume-negrita
duff-campbells-revenge
duke
early-autumn
earth-angel
east-of-the-sun
easter-parade
easy-street
easy-to-love
ebony-rhapsody
el-bimbo
el-bodeguero
el-cumbanchero
eleanor-rigby-alternate
eleanor-rigby
elmers-tune
end-of-a-love-affair
end-of-the-world
eres-tu
estrellita
everybody-loves-my-baby
everybodys-talkin
everything-happens-to-me
everythings-coming-up-roses
evry-night-about-this-time
evry-time-we-say-goodbye
evrything-ive-got
exactly-like-you
falling-in-love-again
falling-in-love-with-love
far-away-places
farolito
favela
feed-the-birds
feelings
fever
fidgety-feet
five-foot-two
flamingo
flowers-on-the-wall
fly-me-to-the-moon
folks-who-live-on-the-hill
fools-rush-in
for-all-we-know
for-every-man-theres-a-woman
for-sentimental-reasons
frenesi
from-me-to-you
from-this-moment-on
fugue-for-tinhorns
garden-in-the-rain
gee-whiz
gentle-rain
georgia-on-my-mind
georgy-girl
get-happy
getting-to-know-you
gigi
girl-from-ipanema
girl-talk
girl
give-me-the-simple-life
glow-worm
god-bless-the-child
gold-diggers-song-the
goldfinger
gonna-get-along
good-morning-heartache
good-night
goodbye
goodnight-my-someone
goody-goody
got-a-date-with-an-angel
grand-night-for-singing
gravy-waltz
great-pretender
green-door
green-eyes
groovin-high
groovy-kind-of-love
guilty
half-as-much
happy-days-and-lonely-nights
happy-days-are-here-again
happy-talk
harbor-lights
hard-hearted-hannah
harlem-nocturne
heart-and-soul
heartaches
heartbeat-its-a-lovebeat
heat-wave
heaven-can-wait
helena-polka
hello-dolly
hello-ma-baby
hello-mary-lou
hello-young-lovers
here-there-and-everywhere
heres-that-rainy-day
hey-jude
hey-good-looking
hey-look-me-over
hey-there
high-hopes
hindustan
hold-me
honey-song
honey
honeysuckle-rose
hooray-for-hollywood
how-about-you
how-high-the-moon
how-insensitive
how-little-we-know
how-long-has-this-been-going-on
huckle-buck
hush-a-bye
i-aint-got-nobody
i-aint-got-nothin-but-the-blues
i-almost-lost-my-mind
i-call-your-name
i-cant-stop-loving-you
i-concentrate-on-you
i-could-have-danced-all-night
i-could-write-a-book
i-cried-for-you
i-didnt-know-what-time-it-was
i-do-i-do
i-dont-want-to-walk-without-you
i-enjoy-being-a-girl
i-fall-to-pieces
i-feel-the-earth-move
i-found-a-million-dollar-baby
i-get-a-kick-out-of-you
i-got-it-bad
i-got-the-sun-in-the-morning
i-have-dreamed
i-left-my-heart-in-san-francisco
i-let-a-song-go-out-of-my-heart
i-love-paris
i-love-you
i-loved-you-once-in-silence
i-married-an-angel
i-only-have-eyes-for-you
i-still-get-jealous
i-surrender-dear
i-talk-to-the-trees
i-thought-about-you
i-wanna-be-loved-by-you
i-want-to-be-happy
i-wanted-to-say
i-was-doing-all-right
i-whistle-a-happy-tune
i-will-always-love-you
i-will-wait-for-you
i-wish-you-love
i-wont-dance
ida-sweet-as-apple-cider
if-i-could-be-with-you-one-hour-tonight
if-i-didnt-care
if-i-fell
if-i-had-my-life-to-live-over
if-i-had-you
if-i-only-had-a-brain
if-i-ruled-the-world
if-i-were-a-bell
if-i-were-a-rich-man
if-you-go
if-you-knew-susie
if-you-love-me-really-love-me
if-you-were-the-only-girl
ill-always-be-in-love-with-you
ill-be-around
ill-be-seeing-you
ill-follow-my-secret-heart
ill-never-smile-again
ill-only-miss-her-when-i-think-of-her
ill-remember-april
ill-see-you-in-my-dreams
ill-string-along-with-you
ill-walk-alone
im-alone-because-i-love-you
im-beginning-to-see-the-light
im-confessin-that-i-love-you
im-falling-in-love-with-someone
im-getting-sentimental-over-you
im-gonna-go-fishin
im-gonna-sit-right-down-and-write-myself-a-letter
im-in-the-mood-for-love
im-just-a-lucky-so-and-so
im-on-my-way
im-sitting-on-top-of-the-world
in-a-mellow-tone
in-a-sentimental-mood
in-a-shanty-in-old-shanty-town
in-my-own-little-corner
in-the-cool-cool-cool-of-the-evening
in-the-still-of-the-night
in-the-still-of-the-nite
in-the-wee-small-hours-of-the-morning
indian-summer
indiana
indifference
ingenuo
into-each-life-some-rain-must-fall
is-you-is-or-is-you-aint
isfahan
isnt-it-a-pity
it-dont-mean-a-thing
it-had-to-be-you
it-might-as-well-be-spring
it-never-entered-my-mind
it-only-takes-a-moment
its-a-good-day
its-all-in-the-game
its-all-right-with-me
its-been-a-long-long-time
its-de-lovely
its-magic
its-not-unusual
its-only-a-paper-moon
its-the-hard-knock-life
its-the-talk-of-the-town
ive-got-a-crush-on-you
ive-got-fidgety-feet
ive-got-my-eyes-on-you
ive-got-my-love-to-keep-me-warm
ive-got-the-world-on-a-string
ive-got-you-under-my-skin
ive-grown-accustomed-her-face
ive-never-been-in-love-before
jada
jalousie
jamaica-farewell
jambalaya
japanese-sandman
java-jive
java
jean
jeepers-creepers
jersey-bounce
johnson-rag
juke-box-saturday-night
julia
june-is-bustin-out-all-over
jungle-drums
just-a-little-while-to-stay-here
just-because
just-in-time
just-like-a-butterfly
just-one-of-those-things
just-squeeze-me
just-walkin-in-the-rain
just-you-just-me
k-k-k-katy
kansas-city
king-of-the-road
knock-three-times
l-o-v-e
la-cumparsita
la-paloma
la-puerta
la-vie-en-rose
lady-in-red
lady-madonna
lady-of-spain
laia-ladaia
lament
last-waltz
laura
lazy-river
lazybones
le-gamin-de-paris
learnin-the-blues
lemon-drop
les-bicyclettes-de-belsize
let-a-smile-be-your-umbrella
let-it-be-me
let-there-be-love
lets-call-the-whole-thing-off
lets-do-it
lets-fall-in-love
lets-misbehave
lets-take-a-walk-around-the-block
liechtensteiner-polka
like-a-lover
like-dreamers-do
lilli-marlene
linda
linger-awhile
lipstick-on-your-collar
little-boat
little-girl-blue
little-jazz-bird
liza
locomotion
lollipop
londonderry-air
lonely-girl
long-ago
look-to-the-sky
looking-for-a-boy
lost-in-meditation
louise
love-for-sale
love-is-a-many-splendored-thing
love-is-blue
love-is-here-to-stay
love-is-just-around-the-corner
love-is-the-tender-trap
love-letters-in-the-sand
love-letters
love-me-do
love-me-or-leave-me
love-me-with-all-your-heart
love-potion-9
love-walked-in
lovely-rita
lover-man
lover
lullaby-of-birdland
lullaby-of-broadway
lulus-back-in-town
lush-life
ma-hes-making-eyes-at-me
mack-the-knife
mad-about-him-sad-without-him
magic-is-the-moonlight
magic-moments
make-believe
make-someone-happy
make-your-own-kind-of-music
makin-whoopee
mame
mamselle
manana
mangos
manhattan
manteca
many-a-new-day
margie
maria
marie
marshmallow-world
martha-my-dear
mas-que-nada
matchmaker-matchmaker
maxwells-silver-hammer
maybe
me-and-my-shadow
mean-to-me
meditation
memories-of-you
memories
memory
mercy-mercy-mercy
michelle
midnight-sun
milord
misery-and-the-blues
miss-otis-regrets
mississippi-mud
missouri-waltz
mister-domingo
misty
mobile
mona-lisa
monday-monday
mood-indigo
moon-love
moon-river
moondance
moonglow
moonlight-becomes-you
moonlight-cocktail
moonlight-in-vermont
moonlight-on-the-ganges
moonlight-saving-time
moonlight-serenade
more-than-you-know
more
morning-has-broken
mountain-greenery
mr-sandman
music-music-music
music-to-watch-girls-by
muskrat-ramble
my-baby-just-cares-for-me
my-blue-heaven
my-buddy
my-cuteys-due-at-two-to-two-today
my-funny-valentine
my-heart-belongs-to-daddy
my-kind-of-girl
my-man
my-old-flame
my-one-and-only-love
my-prayer
my-romance
my-ship
my-special-angel
my-way
nagasaki
nancy-with-the-smiling-face
nardis
nature-boy
naughty-lady-of-shady-lane
nearness-of-you
never-let-me-go
never-my-love
never-on-sunday
nevertheless
new-frankie-song
new-york-new-york
nice-work-if-you-can-get-it
night-and-day
night-train
night-we-called-it-a-day
nine-million-bicycles
no-moon-at-all
no-more-blues
no-other-love
nobody-does-it-better
nobody-i-know
nobody-knows-you-when-youre-down-and-out
non-dimenticar
norwegian-wood
notre-samba
ob-la-di-ob-la-da
oh-by-jingo
oh-johnny-oh
oh-lonesome-me
oh-pretty-woman
oh-you-beautiful-doll
old-cape-cod
old-folks
old-man-river
old-piano-roll-blues
ole-buttermilk-sky
on-the-street-where-you-live
on-the-sunny-side-of-the-street
once-i-loved
once-in-a-while
once-in-love-with-amy
one-boy
one-fine-day
one-for-my-baby
one-note-samba
one-of-those-songs
only-you
ooh-that-kiss
orange-colored-sky
original-dixieland-one-step
original-washington-two-step
our-day-will-come
out-of-my-dreams
over-the-rainbow
paddlin-madelin-home
palabras-de-mujer
paloma-blanca
papa-loves-mambo
paper-doll
paper-roses
paris-mist
pass-me-by
patricia-its-patricia
peacocks
peg-o-my-heart
pennies-from-heaven
pennsylvania-polka
penny-lane
penthouse-serenade
people-will-say-were-in-love
people
perdida
perdido
perfidia
pick-yourself-up
pigalle
pink-panther-theme
please-dont-talk-about-me-when-im-gone
please-please-me
poinciana
polka-dots-and-moonbeams
poor-butterfly
poor-people-of-paris
preacher
precious-little-thing-called-love
prelude-to-a-kiss
pretend
pretty-baby
put-on-a-happy-face
put-on-your-sunday-clothes
puttin-on-the-ritz
quando-quando-quando
que-sera-sera
quiet-nights-of-quiet-stars
quizas-quizas-quizas
rags-to-riches
rainbow
rainy-night-in-georgia
razzle-dazzle
real-live-girl
red-roses-for-a-blue-lady
red-sails-in-the-sunset
rico-vacilon
ridin-high
ring-of-fire
rivers-of-babylon
robbins-nest
rock-a-bye-your-baby-with-a-dixie-melody
rockin-chair
rosa
rose-room
rosie
rosita
round-midnight
route-66
ruby-my-dear
s-h-i-n-e
s-wonderful
sail-along-silvry-moon
samba-de-orfeu
samba-lady
samba-lele
satin-doll
save-the-last-dance-for-me
say-it-isnt-so
scarlet-ribbons
scotch-n-soda
sea-of-love
second-hand-rose
secret-love
sentimental-journey
september-song
serenade-in-blue
serenata
sermonette
sh-boom
shadow-of-your-smile
shangri-la
sheik-of-araby
shes-funny-that-way
shes-just-my-style
shes-leaving-home
shiny-stockings
shoo-fly-pie-and-apple-pan-dowdy
show-me
shuffle-off-to-buffalo
sibony
side-by-side
silencio
silhouettes
sin-un-amor
since-i-dont-have-you
since-i-fell-for-you
sing-for-your-supper
sing
singin-in-the-rain
singing-the-blues
sister-kate
skokiaan
skyfall
skylark
sleep-walk
sleepy-time-gal
slow-boat-to-china
slow-poke
small-fry
smile
smoke-gets-in-your-eyes
smoke-rings
snowfall
snuggled-on-your-shoulder
so-blue
so-danco-samba
so-in-love
so-many-stars
so-nice
so-rare
so-whats-new
solamente-una-vez
solitude
some-day-my-prince-will-come
some-enchanted-evening
some-other-time
somebody-loves-me
someday
someone-to-light-up-my-life
someone-to-watch-over-me
someones-rocking-my-dreamboat
something-good
somethings-gotta-give
somewhere-my-love
somewhere-somehow-someday
song-from-moulin-rouge
song-of-the-jet
song-sung-blue
songs
sonny-boy
sophisticated-lady
soul-eyes
sound-of-silence
south-of-the-border
spanish-eyes
speak-low
speak-up-mambo
spooky
sposin
st-louis-blues
st-thomas
stairway-to-the-stars
stand-by-me
standing-on-the-corner
stardust
stars-fell-on-alabama
stay-as-sweet-as-you-are
stay
steppin-out-with-my-baby
stormy-weather
stranger-in-paradise
stranger-on-the-shore
strangers-in-the-night
stray-cat-strut
street-of-dreams
string-of-pearls
stumbling
subway-harry
sugar-sugar
sugar
sukiyaki
summer-knows
summer-wind
summertime
sunday-kind-of-love
sunday
sunny-side-up
sunny
surrey-with-the-fringe-on-top
suspicion
swanee
sway
sweet-georgia-brown
sweet-lorraine
sweet-sue-just-you
swingin-down-the-lane
swingin-safari
swinging-shepherd-blues
taboo
taint-what-you-do
take-five
take-good-care-of-my-baby
take-the-a-train
take-your-shoes-off-baby
takes-two-to-tango
taking-a-chance-on-love
tammy
tangerine
tango-of-roses
tea-for-two
teenager-in-love
temptation
ten-cents-a-dance
tenderly
tennessee-waltz
thanks-for-the-memory
that-lucky-old-sun
that-old-black-magic
that-old-feeling
thatll-be-the-day
thats-a-plenty
thats-all
thats-entertainment
thats-my-weakness-now
the-gift
the-gypsy
the-lady-is-a-tramp
the-long-and-winding-road
the-man-i-love
the-object-of-my-affection
the-partys-over
the-rose
the-song-is-ended
the-third-man-theme
the-twist
the-waiter-and-the-porter-and-the-upstairs-maid
the-way-you-look-tonight
them-there-eyes
theme-from-mahogany
there-goes-my-heart
there-will-never-be-another-you
therell-be-some-changes-made
theres-a-kind-of-hush
theres-a-lull-in-my-life
theres-a-small-hotel
these-boots-are-made-for-walkin
these-foolish-things
they-all-laughed
they-cant-take-that-away-from-me
they-didnt-believe-me
they-say-its-spring
they-say-its-wonderful
thinking-of-you
this-cant-be-love
this-is-my-song
this-love-of-mine
three-coins-in-the-fountain
tico-tico
tiger-rag
till-then
till-there-was-you
time-after-time
to-know-him-is-to-love-him
todo-todo-todo
together-wherever-we-go
tonight
too-close-for-comfort
too-darn-hot
too-late-now
too-marvelous-for-words
toot-toot-tootsie
top-hat-white-tie-and-tails
top-of-the-world
touch-of-your-lips
traumerei
travlin-light
triste
tristeza
trouble-in-mind
true-love-ways
true-love
try-to-remember
tumbling-tumbleweeds
tuxedo-junction
twilight-time
two-cigarettes-in-the-dark
two-loves-have-i
two-sleepy-people
unchained-melody
undecided
under-a-blanket-of-blue
under-paris-skies
under-the-boardwalk
under-the-bridge-red-hot-chili-peppers
unforgettable
until-the-real-thing-comes-along
up-up-and-away
vaya-con-dios
venus-in-blue-jeans
venus
veracruz
very-early
very-thought-of-you
violets-for-your-furs
vivo-sonhando
volare
vou-vivendo
voyage
wagon-wheels
walk-on-the-wild-side
walkin-after-midnight
walkin-my-baby-back-home
walking-happy
waltz-for-debby
wandrin-star
wang-wang-blues
wasted-days-and-wasted-nights
watch-what-happens
water-is-wide
watermelon-man
wave
way-we-were
wayward-wind
we-have-all-the-time-in-the-world
we-just-couldnt-say-goodbye
we-kiss-in-a-shadow
we-three
wells-fargo-wagon
weve-only-just-begun
what-a-diffrence-a-day-made
what-a-little-moonlight-can-do
what-a-wonderful-world
what-a-wonderful-world
what-is-this-thing-called-love
what-kind-of-fool-am-i
whatll-i-do
whats-new-pussycat
whats-new
whats-the-use
whats-your-name
wheel-of-fortune
when-i-fall-in-love
when-i-grow-too-old
when-i-need-you
when-i-take-my-sugar-to-tea
when-im-sixty-four
when-in-rome
when-irish-eyes-are-smiling
when-its-sleepy-time-down-south
when-lights-are-low
when-my-sugar-walks-down-the-street
when-sunny-gets-blue
when-the-red-red-robin
when-the-world-was-young
when-you-wish-upon-a-star
when-youre-smiling
where-are-you
where-flamingos-fly
where-is-love
where-or-when
where-the-boys-are
whiffenpoof-song
while-my-guitar-gently-weeps
whispering
white-cliffs-of-dover
whiter-shade-of-pale
who
whos-sorry-now
why-do-fools-fall-in-love
why-dont-you-believe-me
why-dont-you-do-right
wild-is-the-wind
willow-weep-for-me
wish-you-were-here
witchcraft
with-a-little-help-from-my-friends
with-a-song-in-my-heart
with-my-eyes-wide-open
without-a-song
wonderland-by-night
world-is-waiting-for-the-sunrise
world-on-fire
world-without-love
would-you-like-to-take-a-walk
wouldnt-it-be-loverly
wrap-your-troubles-in-dreams
wunderbar
yakety-sax
yellow-bird
yellow-days
yes-indeed
yes-sir-aint-she-sweet
yesterday
you-and-the-night-and-the-music
you-are-there
you-belong-to-me
you-call-it-madness
you-cant-go-home-again
you-cant-go-home-again2
you-do-something-to-me
you-dont-own-me
you-go-to-my-head
you-made-me-love-you
you-must-have-been-a-beautiful-baby
you-only-live-twice
you-oughta-be-in-pictures
you-stepped-out-of-a-dream
you-took-advantage-of-me
you-turned-the-tables-on-me
youd-be-so-nice-to-come-home-to
youd-be-surprised
youll-never-get-away-from-me
youll-never-know
young-at-heart
younger-than-springtime
youre-just-in-love
youre-my-everything
youre-sixteen
youre-the-cream-in-my-coffee
youre-the-top
yours
youve-got-to-see-mamma
zing-a-little-zong
zing-went-the-strings-of-my-heart
zingaro
zoo-be-zoo-be-zoo`.split(/[\r\n]+/g);